version: '3.7'

services:
  node-app:
    build: .
    networks:
      - local
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    networks:
      - local
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
      POSTGRES_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    networks:
      - local
    ports:
      - 6379:6379

networks:
  local:
    driver: bridge

volumes:
  db: