version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:14
    networks:
      - local
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
      POSTGRES_DATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
  
  redis:
    image: redis
    networks:
      - local
    ports:
      - "6379:6379"

networks:
  local:
    driver: bridge

volumes:
  db:
